### ISSUE TITLE
Search for episodes within requested season

### ISSUE THREAD

**Issue by Evo-c** [TehMuffinMoo/SonarrThrottling#2]
Hi thanks for the awesome plugin, I was wondering if it would be possible to make it search within seasons rather than the first missing episodes.

At the minute if someone requests say season 5 but season 2 does not exist, it will add x episode threshold from season 2 as it does not exist. Hopefully this makes sense, if not I'll try make a gif to help elaborate.

**Comment by TehMuffinMoo** [comment]
Hey,

Glad you can make use of it!

Yeah, this should be easy enough to do. It does actually do this now, but you have to set the episode(s) as unmonitored rather than the season. This allows you to exclude specific problem epsiodes, or stuff like specials.

Will test it this evening

**Comment by Evo-c** [comment]
Ah I see thanks! For the sake of automation do you think it's possible for Overseerr to pass the season number? Just thinking If so it would be possible to change $Episode['seasonNumber'] != "0" to the season number requested right?

**Comment by TehMuffinMoo** [comment]
Hey, sorry just had a chance to look back at this.

Should be easier than that, the criteria I think you want is already met in the Tautulli webhook in [Line #432](https://github.com/TehMuffinMoo/SonarrThrottling/blob/8943b49d7194cf1733ab67646bacf3635293d76e/plugin.php#L432)

Looks like I never added `&& $Episode['monitored'] == true` to the Overseerr one. This still checks Sonarr on forehand and pulls back all related info into the $Episode variable.

I've pushed an update, fancy giving that a go?

**Comment by Evo-c** [comment]
Appears to work now thanks! This should prevent my queue from being paused from downloading too much before it has a chance to move to a different drive, awesome work.

**Comment by TehMuffinMoo** [comment]
Great news😬 Yeah, It helps with not having to download/upload tonnes of content where it may not even get watched. The Tautulli webhook has been solid for me and those I know who use it for a good few years, even before I converted it to an Organizr plug-in. (Was all scheduled powershell before, gross)

If you ever think of anything else, improvements, changes, or even ideas for plugins as a whole then I’m happy to take suggestions to knob about with in my spare time.
